name: Bug report
about: Create a report to help us improve
title: "[BUG]"
labels: bug
assignees: ''

description: |
  Tell us what happened. In particular, tell us how and why you are using this project,
  and describe the bug that you encountered. Please note that we are not able to support
  all conceivable use cases, but the more information you are able to provide the more
  equipped we will be to help.

steps_to_reproduce: |
  Replace the example steps below with actual steps to reproduce the bug you're reporting.

  1. Go to '...'
  2. Click on '....'
  3. Scroll down to '....'
  4. See error

expected_vs_actual_behavior: |
  What did you expect to happen after you followed the steps you described in the last
  section? What actually happened?

environment: |
  Describe the environment in which you encountered this bug. Use the list below as a
  starting point and add additional information if you think it's relevant.

  - Operating system:
  - Project version/tag: (run 'swanky version')
  - Rust version (run `rustup show`):
  - Node version (run `node --version`)

logs_errors_screenshots: |
  Please provide the text of any logs or errors that you experienced; if applicable,
  provide screenshots to help illustrate the problem.

additional_information: |
  Please add any other details that you think may help us solve your problem.
